const DAYS = {
    MONDAY: 'monday',
    TUESDAY: 'tuesday',
    WEDNESDAY: 'wednesday',
    THURSDAY: 'thursday',
    FRIDAY: 'friday',
    SATURDAY: 'saturday',
    SUNDAY: 'sunday'
};

const DAY_ABBREVIATION = {
    [DAYS.MONDAY]: 'Mon',
    [DAYS.TUESDAY]: 'Tue',
    [DAYS.WEDNESDAY]: 'Wed',
    [DAYS.THURSDAY]: 'Thu',
    [DAYS.FRIDAY]: 'Fri',
    [DAYS.SATURDAY]: 'Sat',
    [DAYS.SUNDAY]: 'Sun'
};

const DAY_SINGLE_LETTER_ABBREVIATION = {
    [DAYS.MONDAY]: 'M',
    [DAYS.TUESDAY]: 'T',
    [DAYS.WEDNESDAY]: 'W',
    [DAYS.THURSDAY]: 'T',
    [DAYS.FRIDAY]: 'F',
    [DAYS.SATURDAY]: 'S',
    [DAYS.SUNDAY]: 'S'
};

export const TABLE_HEADERS = [
    DAY_SINGLE_LETTER_ABBREVIATION[DAYS.SUNDAY],
    DAY_SINGLE_LETTER_ABBREVIATION[DAYS.MONDAY],
    DAY_SINGLE_LETTER_ABBREVIATION[DAYS.TUESDAY],
    DAY_SINGLE_LETTER_ABBREVIATION[DAYS.WEDNESDAY],
    DAY_SINGLE_LETTER_ABBREVIATION[DAYS.THURSDAY],
    DAY_SINGLE_LETTER_ABBREVIATION[DAYS.FRIDAY],
    DAY_SINGLE_LETTER_ABBREVIATION[DAYS.SATURDAY]
];

export const weatherIcons = {
    PARTLY_SUNNY: '',
    SUN: ''
};